/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Monaco } from "@monaco-editor/loader";
import { editor } from "monaco-editor";
export namespace Components {
    interface AppFileMenu {
        "exitHandler": () => void;
        "newFileHandler": () => void;
        "openFileHandler": () => void;
        "popoverId": string;
        "saveFileAsHandler": () => void;
        "saveFileHandler": () => void;
    }
    interface AppHome {
        "editorLanguage": string;
        "sharedContentBase64": string;
    }
    interface AppMonacoEditor {
        "language": string;
        "theme": string;
        "value": string;
    }
    interface AppRoot {
    }
    interface AppSettingMenu {
        "updateEditorThemeHandler": (theme: 'light' | 'dark') => void;
    }
}
declare global {
    interface HTMLAppFileMenuElement extends Components.AppFileMenu, HTMLStencilElement {
    }
    var HTMLAppFileMenuElement: {
        prototype: HTMLAppFileMenuElement;
        new (): HTMLAppFileMenuElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMonacoEditorElement extends Components.AppMonacoEditor, HTMLStencilElement {
    }
    var HTMLAppMonacoEditorElement: {
        prototype: HTMLAppMonacoEditorElement;
        new (): HTMLAppMonacoEditorElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingMenuElement extends Components.AppSettingMenu, HTMLStencilElement {
    }
    var HTMLAppSettingMenuElement: {
        prototype: HTMLAppSettingMenuElement;
        new (): HTMLAppSettingMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-file-menu": HTMLAppFileMenuElement;
        "app-home": HTMLAppHomeElement;
        "app-monaco-editor": HTMLAppMonacoEditorElement;
        "app-root": HTMLAppRootElement;
        "app-setting-menu": HTMLAppSettingMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppFileMenu {
        "exitHandler"?: () => void;
        "newFileHandler"?: () => void;
        "openFileHandler"?: () => void;
        "popoverId"?: string;
        "saveFileAsHandler"?: () => void;
        "saveFileHandler"?: () => void;
    }
    interface AppHome {
        "editorLanguage"?: string;
        "sharedContentBase64"?: string;
    }
    interface AppMonacoEditor {
        "language"?: string;
        "onComponentLoad"?: (event: CustomEvent<Monaco>) => void;
        "onDidChangeModelContent"?: (event: CustomEvent<editor.IModelContentChangedEvent>) => void;
        "theme"?: string;
        "value"?: string;
    }
    interface AppRoot {
    }
    interface AppSettingMenu {
        "updateEditorThemeHandler"?: (theme: 'light' | 'dark') => void;
    }
    interface IntrinsicElements {
        "app-file-menu": AppFileMenu;
        "app-home": AppHome;
        "app-monaco-editor": AppMonacoEditor;
        "app-root": AppRoot;
        "app-setting-menu": AppSettingMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-file-menu": LocalJSX.AppFileMenu & JSXBase.HTMLAttributes<HTMLAppFileMenuElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-monaco-editor": LocalJSX.AppMonacoEditor & JSXBase.HTMLAttributes<HTMLAppMonacoEditorElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-setting-menu": LocalJSX.AppSettingMenu & JSXBase.HTMLAttributes<HTMLAppSettingMenuElement>;
        }
    }
}
