/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFileMenu {
        "exitHandler": () => void;
        "newFileHandler": () => void;
        "openFileHandler": () => void;
        "popoverId": string;
        "saveFileAsHandler": () => void;
        "saveFileHandler": () => void;
    }
    interface AppHome {
        "sharedContentBase64": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppFileMenuElement extends Components.AppFileMenu, HTMLStencilElement {
    }
    var HTMLAppFileMenuElement: {
        prototype: HTMLAppFileMenuElement;
        new (): HTMLAppFileMenuElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-file-menu": HTMLAppFileMenuElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppFileMenu {
        "exitHandler"?: () => void;
        "newFileHandler"?: () => void;
        "openFileHandler"?: () => void;
        "popoverId"?: string;
        "saveFileAsHandler"?: () => void;
        "saveFileHandler"?: () => void;
    }
    interface AppHome {
        "sharedContentBase64"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-file-menu": AppFileMenu;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-file-menu": LocalJSX.AppFileMenu & JSXBase.HTMLAttributes<HTMLAppFileMenuElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
